<?php
// Start session if not already started
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Include required files
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../utils/Auth.php';

// Initialize Auth
$auth = Auth::getInstance();

// Check if user is admin
if (!$auth->isAdmin()) {
    header('Location: ../access-denied.php');
    exit;
}

// Check if content and title are provided
if (!isset($_POST['content']) || !isset($_POST['title'])) {
    die('Missing required parameters');
}

$title = $_POST['title'];
$content = $_POST['content'];
$date = date('Y-m-d H:i:s');

// Generate print-friendly HTML output
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($title); ?></title>
    <style>
        @media print {
            body {
                margin: 0;
                padding: 0;
                font-family: Arial, Helvetica, sans-serif;
            }
            .print-header {
                text-align: center;
                border-bottom: 1px solid #000;
                padding-bottom: 10px;
                margin-bottom: 20px;
            }
            .print-footer {
                text-align: center;
                border-top: 1px solid #000;
                padding-top: 10px;
                margin-top: 20px;
                font-size: 12px;
            }
            .no-print {
                display: none;
            }
            table {
                width: 100%;
                border-collapse: collapse;
            }
            table, th, td {
                border: 1px solid #000;
            }
            th, td {
                padding: 5px;
            }
        }
        
        body {
            margin: 30px;
            padding: 20px;
            font-family: Arial, Helvetica, sans-serif;
        }
        .print-header {
            text-align: center;
            border-bottom: 1px solid #000;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .print-footer {
            text-align: center;
            border-top: 1px solid #000;
            padding-top: 10px;
            margin-top: 20px;
            font-size: 12px;
        }
        .no-print {
            background-color: #f4f4f4;
            padding: 10px;
            margin: 20px 0;
            text-align: center;
        }
        .no-print button {
            padding: 10px 20px;
            margin: 0 10px;
            cursor: pointer;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        table, th, td {
            border: 1px solid #000;
        }
        th, td {
            padding: 8px;
        }
    </style>
</head>
<body>
    <div class="no-print">
        <h3>PDF Generation</h3>
        <p>Use your browser's print function (Ctrl+P or Command+P) to save this page as a PDF.</p>
        <button onclick="window.print()">Print</button>
        <button onclick="window.history.back()">Go Back</button>
    </div>

    <div class="print-header">
        <h1><?php echo htmlspecialchars($title); ?></h1>
        <p>Generated on: <?php echo $date; ?></p>
    </div>

    <div class="print-content">
        <?php echo $content; ?>
    </div>

    <div class="print-footer">
        <p>This document was generated by the Lab Management System.</p>
        <p>Copyright © <?php echo date('Y'); ?> - All rights reserved</p>
    </div>

    <script>
        // Auto-trigger print dialog when page loads (optional)
        //window.onload = function() {
        //    setTimeout(function() {
        //        window.print();
        //    }, 1000);
        //};
    </script>
</body>
</html> 